### ISSUE TITLE
Terkait menu transaksi

### ISSUE THREAD

**Issue by deib97** [hidayat365/yii2-inventory-app#1]
Untuk menu /transaction/out dan /transaction/in
Tidak bisa ditemukan ya pak? Apakah ada yang kurang sourcenya?

**Comment by hidayat365** [comment]
> Untuk menu /transaction/out dan /transaction/in Tidak bisa ditemukan ya pak? Apakah ada yang kurang sourcenya?

in progress, sedang ditambahkan

**Comment by hidayat365** [comment]
closed #2
please check realese [v1.0.2](https://github.com/hidayat365/yii2-inventory-app/releases/tag/v1.0.2)
